services:
  mysql:
    image: mysql:8.0
    container_name: medical-appointment-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: medical_appointment_db
    ports:
      - "3306:3306"
    volumes:
      - medical_appointment_data:/var/lib/mysql

volumes:
  medical_appointment_data: